<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([
            ['city_name' => 'Banda Aceh'],
            ['city_name' => 'Langsa'],
            ['city_name' => 'Lhokseumawe'],
            ['city_name' => 'Sabang'],
            ['city_name' => 'Subulussalam'],
            ['city_name' => 'Denpasar'],
            ['city_name' => 'Pangkalpinang'],
            ['city_name' => 'Cilegon'],
            ['city_name' => 'Serang'],
            ['city_name' => 'Tangerang Selatan'],
            ['city_name' => 'Tangerang'],
            ['city_name' => 'Bengkulu'],
            ['city_name' => 'Yogyakarta'],
            ['city_name' => 'Gorontalo'],
            ['city_name' => 'Kota Administrasi Jakarta Barat'],
            ['city_name' => 'Kota Administrasi Jakarta Pusat'],
            ['city_name' => 'Kota Administrasi Jakarta Selatan'],
            ['city_name' => 'Kota Administrasi Jakarta Timur'],
            ['city_name' => 'Kota Administrasi Jakarta Utara'],
            ['city_name' => 'Sungai Penuh'],
            ['city_name' => 'Jambi'],
            ['city_name' => 'Bandung'],
            ['city_name' => 'Bekasi'],
            ['city_name' => 'Bogor'],
            ['city_name' => 'Cimahi'],
            ['city_name' => 'Cirebon'],
            ['city_name' => 'Depok'],
            ['city_name' => 'Sukabumi'],
            ['city_name' => 'Tasikmalaya'],
            ['city_name' => 'Banjar'],
            ['city_name' => 'Magelang'],
            ['city_name' => 'Pekalongan'],
            ['city_name' => 'Salatiga'],
            ['city_name' => 'Semarang'],
            ['city_name' => 'Surakarta'],
            ['city_name' => 'Tegal'],
            ['city_name' => 'Batu'],
            ['city_name' => 'Blitar'],
            ['city_name' => 'Kediri'],
            ['city_name' => 'Madiun'],
            ['city_name' => 'Malang'],
            ['city_name' => 'Mojokerto'],
            ['city_name' => 'Pasuruan'],
            ['city_name' => 'Probolinggo'],
            ['city_name' => 'Surabaya'],
            ['city_name' => 'Pontianak'],
            ['city_name' => 'Singkawang'],
            ['city_name' => 'Banjarbaru'],
            ['city_name' => 'Banjarmasin'],
            ['city_name' => 'Palangka Raya'],
            ['city_name' => 'Balikpapan'],
            ['city_name' => 'Bontang'],
            ['city_name' => 'Samarinda'],
            ['city_name' => 'Nusantara'],
            ['city_name' => 'Tarakan'],
            ['city_name' => 'Batam'],
            ['city_name' => 'Tanjungpinang'],
            ['city_name' => 'Bandar Lampung'],
            ['city_name' => 'Metro'],
            ['city_name' => 'Ternate'],
            ['city_name' => 'Tidore Kepulauan'],
            ['city_name' => 'Ambon'],
            ['city_name' => 'Tual'],
            ['city_name' => 'Bima'],
            ['city_name' => 'Mataram'],
            ['city_name' => 'Kupang'],
            ['city_name' => 'Sorong'],
            ['city_name' => 'Jayapura'],
            ['city_name' => 'Dumai'],
            ['city_name' => 'Pekanbaru'],
            ['city_name' => 'Makassar'],
            ['city_name' => 'Palopo'],
            ['city_name' => 'Parepare'],
            ['city_name' => 'Palu'],
            ['city_name' => 'Baubau'],
            ['city_name' => 'Kendari'],
            ['city_name' => 'Bitung'],
            ['city_name' => 'Kotamobagu'],
            ['city_name' => 'Manado'],
            ['city_name' => 'Tomohon'],
            ['city_name' => 'Bukittinggi'],
            ['city_name' => 'Padang'],
            ['city_name' => 'Padang Panjang'],
            ['city_name' => 'Pariaman'],
            ['city_name' => 'Payakumbuh'],
            ['city_name' => 'Sawahlunto'],
            ['city_name' => 'Solok'],
            ['city_name' => 'Lubuklinggau'],
            ['city_name' => 'Pagar Alam'],
            ['city_name' => 'Palembang'],
            ['city_name' => 'Prabumulih'],
            ['city_name' => 'Binjai'],
            ['city_name' => 'Gunungsitoli'],
            ['city_name' => 'Medan'],
            ['city_name' => 'Padangsidimpuan'],
            ['city_name' => 'Pematangsiantar'],
            ['city_name' => 'Sibolga'],
            ['city_name' => 'Tanjungbalai'],
            ['city_name' => 'Tebing Tinggi'],
        ]);
    }
}
